ITShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('category-list', views.category_list, name='category-list'),
    path('brand-list', views.brand_list, name='brand-list'),
    path('product-list', views.product_list, name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product_detail'),
    path('filter-data',views.filter_data,name='filter_data'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('add-to-cart',views.add_to_cart,name='add_to_cart'),
    path('cart',views.cart_list,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('accounts/signup',views.signup,name='signup'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='login'),
    path('checkout',views.checkout,name='checkout'),
    path('save-review/<int:pid>',views.save_review,name='save-review'),
    # User Section Start
    path('my-dashboard',views.my_dashboard,name='my_dashboard'),
    path('my-orders',views.my_orders,name='my_orders'),
    path('my-orders-items/<int:id>',views.my_order_items,name='my_order_items'),
    # End
    
    # Wishlist
    path('add-wishlist',views.add_wishlist,name='add_wishlist'),
    path('my-wishlist',views.my_wishlist,name='my_wishlist'),
    # My Reviews
    path('my-reviews',views.my_reviews,name='my-reviews'),
    # My AddressBook
    path('my-addressbook',views.my_addressbook,name='my-addressbook'),
    path('add-address',views.save_address,name='add-address'),
    path('activate-address',views.activate_address, name='activate-address'),
    path('update-address/<int:id>',views.update_address, name='update-address'),
    path('edit-profile',views.edit_profile, name='edit-profile'),
    path('payment',views.payment, name='payment'),
    path('delete-wishlist',views.delete_wishlist, name='delete-wishlist'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Banner
class Banner(models.Model):
    img=models.ImageField(upload_to="banner_imgs/")
    alt_text = models.CharField(max_length=300)
    
    class Meta:
        verbose_name_plural='1. Banners'
        
    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))
        
    def __str__(self):
        return self.alt_text
    
# Category
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")
    
    class Meta:
        verbose_name_plural = '2. Categories'
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.image.url))

    def __str__(self):
        return self.title

# Brand
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_imgs/")
    
    class Meta:
        verbose_name_plural='3. Brands'
    
    def __str__(self):
        return self.title

# Color
class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural='4. Colors'
        
    def color_bg(self):
        return mark_safe('<div style="width:30px; height:30px; background-color:%s"></div>' % (self.color_code))
    
    def __str__(self):
        return self.title
    
# Product Model
class Product(models.Model):
    
    def get_average_rating(self):
        reviews = ProductReview.objects.filter(product=self)
        if reviews:
            total_ratings = sum([int(review.review_rating) for review in reviews])
            return total_ratings / len(reviews)
        return 0

    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural='5. Products'
    
    def __str__(self):
        return self.title
    
# Product Attribute
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="product_imgs/", null=True)
    
    class Meta:
        verbose_name_plural='6. ProductAttributes'
    
    def __str__(self):
        return self.product.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.image.url))
    
# Order
status_choice=(
    ('process','In Process'),
    ('shipped','Shipped'),
    ('delivered','Delivered'),
)
class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amt = models.FloatField()
    paid_status = models.BooleanField(default=False)
    order_dt = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(choices=status_choice,default='process',max_length=150)
    
    class Meta:
        verbose_name_plural='7. Orders'
    
# OrderItems
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    order_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    order_dt = models.DateTimeField(auto_now_add=True)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()
    
    class Meta:
        verbose_name_plural='8. Orders details'
        
    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="100" />' % (self.image))
    
# Product Review
RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)
    
    def get_review_rating(self):
        return self.review_rating
    
    '''
    def get_review_rating(self):
        return str(self.review_rating) if self.review_rating is not None else '0'
    '''
    
    class Meta:
        verbose_name_plural='9. Reviews'

# WishList
class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural='Wishlist'
    
# AddressBook
class UserAddressBook(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mobile=models.IntegerField(null=True)
    address=models.TextField()
    status=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='AddressBook'

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse,HttpResponseRedirect
from .models import Banner,Category,Brand,Product,ProductAttribute,CartOrder,CartOrderItems,ProductReview,Wishlist,UserAddressBook
from django.template.loader import render_to_string
from django.db.models import Max,Min,Count,Avg
from django.db.models.functions import ExtractMonth
from .forms import SignupForm,ReviewAdd,AddressBookForm,ProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView

# Home Page
def home(request):
    banners = Banner.objects.all().order_by('-id')
    products = Product.objects.filter(is_featured=True).order_by('-id')
    products_with_ratings = []
    for product in products:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    return render(request, 'index.html', {'products': products_with_ratings, 'banners': banners})


# Category
def category_list(request):
    data = Category.objects.all().order_by('-id')
    return render(request,'category_list.html', {'data':data})

# Brand
def brand_list(request):
    data = Brand.objects.all().order_by('-id')
    return render(request,'brand_list.html', {'data':data})

# Product List
def product_list(request):
    total_data = Product.objects.count()
    products = Product.objects.all().order_by('-id')[:3]
    min_price = ProductAttribute.objects.aggregate(Min('price'))
    max_price = ProductAttribute.objects.aggregate(Max('price'))
    products_with_ratings = []
    for product in products:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    
    return render(request,'product_list.html',
        {
            'products': products_with_ratings,
            'total_data': total_data,
            'min_price': min_price,
            'max_price': max_price
        }
        )
    
# Product List According to Category
def category_product_list(request,cat_id):
    category = Category.objects.get(id=cat_id)
    data = Product.objects.filter(category=category).order_by('-id')
    products_with_ratings = []
    for product in data:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    return render(request,'category_product_list.html',
        {
            'products': products_with_ratings,
        }
        )
 
# Product List According to Brand
def brand_product_list(request,brand_id):
    brand = Brand.objects.get(id=brand_id)
    data = Product.objects.filter(brand=brand).order_by('-id')
    products_with_ratings = []
    for product in data:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    return render(request,'brand_product_list.html',
        {
            'products': products_with_ratings,
        }
        )

# Product Detail
@login_required(login_url='login')  # add this decorator to check if user is authenticated
def product_detail(request, slug, id):
    product = get_object_or_404(Product, slug=slug, id=id)
    related_products = Product.objects.filter(category=product.category).exclude(id=id)[:4]
    colors = ProductAttribute.objects.filter(product=product).values('color__id','color__title','color__color_code').distinct()
    reviewForm = ReviewAdd()
    
    # Check
    canAdd = True
    reviewCheck = ProductReview.objects.filter(user=request.user,product=product).count()
    if request.user.is_authenticated:
        if reviewCheck > 0:
            canAdd = False
    # End
    
    # Fetch reviews
    reviews = ProductReview.objects.filter(product=product)
    #End
    
    # Fetch avg rating for reviews
    avg_reviews = ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
    if avg_reviews['avg_rating'] is None:
        avg_reviews['avg_rating'] = 0
	# End
    return render(request, 'product_detail.html',{'data':product, 'related':related_products, 'colors': colors,'reviewForm': reviewForm,'canAdd':canAdd,'reviews':reviews,'avg_reviews':avg_reviews})

# Search
def search(request):
    q = request.GET['q']
    data = Product.objects.filter(title__icontains=q).order_by('-id')
    return render(request, 'search.html', {'data':data})

# Filter Data
def filter_data(request):
    colors = request.GET.getlist('color[]')
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    minPrice = request.GET['minPrice']
    maxPrice = request.GET['maxPrice']
    allProducts = Product.objects.all().order_by('-id').distinct()
    allProducts = allProducts.filter(productattribute__price__gte=minPrice)
    allProducts = allProducts.filter(productattribute__price__lte=maxPrice)
    if len(colors)>0:
        allProducts = allProducts.filter(productattribute__color__id__in=colors).distinct()
    if len(categories)>0:
        allProducts = allProducts.filter(category__id__in=categories).distinct()
    if len(brands)>0:
        allProducts = allProducts.filter(brand__id__in=brands).distinct()
        
    products_with_ratings = []
    for product in allProducts:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    context = {
        'is_authenticated': request.user.is_authenticated,
        'products': products_with_ratings
    }
    t = render_to_string('ajax/product-list.html',context)
    
    return JsonResponse({'data':t})

def load_more_data(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    colors = request.GET.getlist('color[]')
    categories = request.GET.getlist('category[]')
    brands = request.GET.getlist('brand[]')
    minPrice = request.GET['minPrice']
    maxPrice = request.GET['maxPrice']
    allProducts = Product.objects.all().order_by('-id').distinct()
    allProducts = allProducts.filter(productattribute__price__gte=minPrice)
    allProducts = allProducts.filter(productattribute__price__lte=maxPrice)
    if len(colors)>0:
        allProducts = allProducts.filter(productattribute__color__id__in=colors).distinct()
    if len(categories)>0:
        allProducts = allProducts.filter(category__id__in=categories).distinct()
    if len(brands)>0:
        allProducts = allProducts.filter(brand__id__in=brands).distinct()
        
    products_with_ratings = []
    for product in allProducts:
        avg_rating = product.get_average_rating()
        products_with_ratings.append((product, avg_rating))
    context = {
        'is_authenticated': request.user.is_authenticated,
        'products': products_with_ratings[offset:offset+limit]
    }
    t = render_to_string('ajax/product-list.html',context)
    return JsonResponse({'data':t})


# Add to cart
def add_to_cart(request):
    # del request.session['cartdata']
    cart_p = {}
    cart_p[request.GET['id']] = {
        'image': request.GET['image'],
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price']
    }
    
    if 'cartdata' in request.session:
        if request.GET['id'] in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[request.GET['id']]['qty'] = cart_p[request.GET['id']]['qty']
            cart_data.update(cart_data)
            request.session['cartdata'] = cart_data
        else:
            cart_data = request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata'] = cart_data
    else:
        request.session['cartdata'] = cart_p 
    return JsonResponse({'data': request.session['cartdata'], 'totalitems':len(request.session['cartdata'])})

# Cart List Page
def cart_list(request):
	total_amt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			total_amt += int(item['qty']) * float(item['price'])
		return render(request, 'cart.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
	else:
		return render(request, 'cart.html',{'cart_data':'','totalitems':0,'total_amt':total_amt})

# Delete Cart Item
def delete_cart_item(request):
    p_id = str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            del cart_data[p_id]
            cart_data.update(cart_data)
            request.session['cartdata'] = cart_data
    total_amt=0
    if 'cartdata' in request.session:
        for p_id,item in request.session['cartdata'].items():
            total_amt+=int(item['qty'])*float(item['price'])
            
    t = render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return JsonResponse({'data':t, 'totalitems':len(request.session['cartdata'])})

# Update Cart Item
def update_cart_item(request):
	p_id=request.GET['id']
	p_qty=request.GET['qty']
 
	if 'cartdata' in request.session:
		if p_id in request.session['cartdata']:
			cart_data=request.session['cartdata']
			cart_data[request.GET['id']]['qty']=p_qty
			request.session['cartdata']=cart_data
   
	total_amt=0
 
	for p_id,item in request.session['cartdata'].items():
		total_amt+=int(item['qty'])*float(item['price'])
  
	t=render_to_string('ajax/cart-list.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})

	return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

# SignUp
def signup(request):
    
    if request.method == 'POST':
        form = SignupForm(request.POST)
        

main/templates/brand_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product, avg_rating in products %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
			    		<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> DT</h6>	    
					  </div>
					    <div class="card-footer">
						    <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						    <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
							<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
							<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
							<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
							{% if user.is_authenticated %}
							<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
						    {% else %}
						    <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
						    {% endif %}
						    <span class="float-right">
								{{ avg_rating }}/5
							<i class="fa fa-star text-warning"></i>
							</span>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product, avg_rating in products %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
			    		<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> DT</h6>	    
					  </div>
					<div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
						<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
						<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
						<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
						{% if user.is_authenticated %}
						<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
						{% else %}
						<button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
						{% endif %}
						<span class="float-right">
							{{ avg_rating }}/5
						<i class="fa fa-star text-warning"></i>
						</span>
					</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
      {% endif %}
      <img src="/media/{{banner.img}}" class="d-block w-100" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
    {% for product, avg_rating in products %}
		<div class="col-md-3 mb-4">
			  <div class="card shadow">
          <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			    <div class="card-body">
          <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
			    <h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> DT</h6>
          </div>
			  <div class="card-footer">
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
		      <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
		      <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
			  	{% if user.is_authenticated %}
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
          {% else %}
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
          {% endif %}
          <span class="float-right">
			  	  {{ avg_rating }}/5
			  	  <i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

main/templates/payment.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Payment</title>
</head>
<body>
	
    <form method="POST">
			{% csrf_token %}

			
			<button type="submit">Envoyer</button>
    </form>
    
</body>
</html>

main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product, avg_rating in products %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
			    		<h6><span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span> DT</h6>	    
					</div>
					<div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
		                <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
		                <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	        <button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
			  	        {% if user.is_authenticated %}
			  	        <button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
                        {% else %}
                        <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
                        {% endif %}
                        <span class="float-right">
							{{ avg_rating }}/5
			  		    <i class="fa fa-star text-warning"></i>
			  	        </span>
			        </div>
				</div>
			</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}